services:
  - type: web
    name: chatbot-cv
    env: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    healthCheckPath: /
